server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_rest
    username: admin
    password: admin_password
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN
jwt:
  header: Authorization
  prefix: Bearer
cors:
  allowed-origins: "http://localhost:3000, http://127.0.0.1:3000"
  allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
  allowed-headers: "*"
  exposed-headers: "Authorization"
  allow-credentials: true
  max-age: 3600
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    persist-authorization: true
  api-docs:
    groups:
      admin:
        display-name: Admin API
        paths-to-match: /api/admin/**
      user:
        display-name: User API
        paths-to-match: /api/user/**
  jwt:
    enabled: true